### ISSUE TITLE
Corpses don't hide anymore

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#14]
**Versions (please complete the following information)**
 - Unity Version: **2018.4.1**
 - uMMORPG Version: **1.171**
 - Are you using a fresh uMMORPG version without any modifications? **yes**
 
**Describe the bug**
Corpses of dead monsters (and in fact all kinds of networked objects using a proximity grid checker) are not hidden when they die. You can see that on "Network Proximity Grid Checker" the "Force Hidden" Flag is set on the server, but it has no effect on clients.

Important Note: It works in Host+Play but not as Server and separate Client !!!

**To Reproduce**
Simply import latest, unmodified uMMORPG3d into unity and kill a few skeletons. You can even set "death time" to 0. Their corpses stay around forever.

**Expected behavior**
Corpses should hide after death time elapsed.

**System (please complete the following information):**
 - Operating System : Mac OS

![unknown](https://user-images.githubusercontent.com/40817126/59288510-4009f480-8c74-11e9-8e7f-7ed7153e46d1.png)

**Comment by Ghetaldus** [comment]
Just found where bug is.
In NetworkProximityGridChecker.cs on line 124 you are doing "return true" when checking forceHidden. It should be false as it is in NetworkProximityChecker.cs in Mirror.
I have just tested changing it to true and corpses disappear fine now.

**Comment by gummby8** [comment]
Having the same issue with 2d
I think he got his bool mixed up. 
It is currently set to false, it should be true

Should look like this, at least on UMMORPG2d

    // called when a new player enters
    public override bool OnCheckObserver(NetworkConnection newObserver)
    {
        if (forceHidden)
            return true;

        // calculate projected positions
        Vector2Int projected = ProjectToGrid(transform.position);
        Vector2Int observerProjected = ProjectToGrid(newObserver.playerController.transform.position);

        // distance needs to be at max one of the 8 neighbors, which is
        //   1 for the direct neighbors
        //   1.41 for the diagonal neighbors (= sqrt(2))
        return Vector2Int.Distance(projected, observerProjected) <= Mathf.Sqrt(2);
    }



    public override bool OnRebuildObservers(HashSet<NetworkConnection> observers, bool initial)
    {
        // only add self as observer if force hidden
        if (forceHidden)
            return true;

        // add everyone in 9 neighbour grid
        Vector2Int current = ProjectToGrid(transform.position);
        HashSet<NetworkConnection> hashSet = grid.GetWithNeighbours(current);
        observers.UnionWith(hashSet);

        // always return true when overwriting OnRebuildObservers so that
        // Mirror knows not to use the built in rebuild method.
        return true;
    }

**Comment by miwarnec** [comment]
fixed in latest version, thanks for reporting

**Comment by Ghetaldus** [comment]
Well it is not fixed for uMMORPG in latest version.
You have fixed it in NetworkProximityChecker.cs in Mirror. uMMORPG uses NetworkProximityGridChecker.cs that is not part of Mirror and that one have same error as well.
